### ISSUE TITLE
Artifacts and Proxies should ignore Abstract types

### ISSUE THREAD

**Issue by smithmx** [dolittle/DotNET.SDK#136]
There's a scenario where you want a base read model that handles basic scenarios (e.g. Id to _id for mongo, a well known field for a surrogate Key, etc).

We don't want this to be treated as an artifact in itself or a proxy generated.  Also, if it's generic our naming doesn't work (e.g. BaseReadModel'1).

We just need to ensure all properties from the base class are on the proxy.

**Comment by woksin** [comment]
@einari should probably join the discussion

**Comment by einari** [comment]
Makes sense. We can ignore abstract types - they're not possible to instantiate anyways.  As for the Generic issue - we could argue that it is not an artifact either - we don't know how to instantiate a generic type without having the type to provide as generic argument, so I suggest we ignore those as well.
