### ISSUE TITLE
Application Artifact Identifier does not play nice with our _ convention

### ISSUE THREAD

**Issue by smithmx** [dolittle/DotNET.SDK#21]

**Comment by smithmx** [comment]
I have a command with the following identifier:

"PortCostPlanner#commodity_planner.port_commodities-record_price_for_commodity_in_port+Command|Domain" (taken from the proxy generation.

When using the IApplicationArtifactIdentifier to find the correct handler method to invoke, it does not find any.  The Artifact identifier for the invoke method that is stored in CommandHandlerInvoker has the same Application and Area but the Location and Artifact do not match.  There's no obvious reason why the Artifacts do not match (they have the same values) but the Location is different.  The version that is used to key the invoker method is correct - it has two parts, Bounded Context (commodity_planner) and Feature (port_commodities).  The version derived from the command has only Bounded Context (commodity_planner).  It is missing the feature.

It works comparing strings because neither version included the Feature in the string output.
"PortCostPlanner - Domain - record_price_for_commodity_in_port @ Dolittle.Applications.ApplicationLocation"

**Comment by einari** [comment]
child of #25

**Comment by woksin** [comment]
This problem should have been resolved now by the changes in SDK and Fundamentals.
Can we have someone confirm this?
