### ISSUE TITLE
Exceptions in CommandHandlers are swallowed when trying to handle commands

### ISSUE THREAD

**Issue by pavsaund** [dolittle/DotNET.SDK#52]
It looks like exceptions in `CommandHandlers` are swallowed when trying to handle commands. Kudos to @yngvebn for spotting this.

https://github.com/dolittle/DotNET.SDK/blob/bc8aa881ad38d64235ca4506d4b16a5dec297d32/Source/Commands.Handling/CommandHandlerInvoker.cs#L108-L116

**Comment by einari** [comment]
We should also return the correct expected HTTP error code for the different things in command result

**Comment by yngvebn** [comment]
@einari imho Http codes does not belong here. This part of the code should not make assumptions about the caller. Mapping to a Http error code should be done in the webapi layer where the commandexecutor is invoked. Still only my opinion 😊

**Comment by einari** [comment]
You're absolutely right @yngvebn - the HTTP error codes should be generated on the Command and Query controllers found [here](https://github.com/dolittle-interaction/AspNetCore)

**Comment by einari** [comment]
Added issues; https://github.com/dolittle-interaction/AspNetCore/issues/23 & https://github.com/dolittle-interaction/AspNetCore/issues/24
