### ISSUE TITLE
In Artifacts.Tooling, consider having an option to say a base namespace.

### ISSUE THREAD

**Issue by woksin** [dolittle/DotNET.SDK#53]
child of #25 
E.g. for Web projects (see Sentry) - we tend to have Features/ root folder.

This configuration should then be optional and default set to empty. The MSBuild task should expose a variable that can be set in a `<PropertyGroup/>`
 
The base namespace would be from the second segment - after tier segment

**Comment by einari** [comment]
Come to think of it; it probably shouldn't have this in the `<PropertyGroup/>` configuration - for consistency.  Since we have `UseModules` in the bounded context configuration, this could be there as well.

**Comment by einari** [comment]
Or, never mind.. :) 
Ramblings of a madman. 

`<PropertyGroup/>` in the `.csproj` makes sense for this.
