### ISSUE TITLE
Add Proxy generation to the Dolittle SDK CLI tool for common artifacts

### ISSUE THREAD

**Issue by einari** [dolittle/DotNET.SDK#59]
child of #57

The proxy generation should look into the types of the output assembly and look for artifacts we want to have represented in the frontend.
The resulting JavaScript file should sit side by side to the original file. So for instance: `Domain/SomeModule/SomeFeature/MyCommand.cs` would have a JS file : `Domain/SomeModule/SomeFeature/MyCommand.js`

BabelJS provides an AST to work with and there is a wrapper for .NET that can access this model - described here : https://babeljs.io/en/setup#installation (Click the C#/.NET) - its been built for React, but we can tap into it - more details: https://reactjs.net

Our primary objective is JavaScript - ES201x style. 

The base type is here: 
https://github.com/dolittle-interaction/JavaScript.Client/blob/master/Source/commands/Command.js

One can assume that the package `@dolittle/commands` is present and extend the command: https://github.com/dolittle-interaction/JavaScript.Client/blob/master/Source/commands/Command.js

Same goes for `@dolittle/commands`

Example expected proxy result for a command: 

```javascript
import { Command } from '@dolittle/commands/Command';

export class MyCommand extends Command
{
   constructor() {
       super();
       this.type = '<guid of type>';
   }
}

```

We need proxies for:

- [x] Command Proxies
- [ ] Read Model Proxies
- [ ] Query Proxies

**Comment by einari** [comment]
Lets change strategy; drop Babel - go for simpler templating engine using Handlebars.

https://github.com/rexm/Handlebars.Net

Example of template:

```javascript
import { Command } from  '@dolittle/commands/Command';

export class {{commandName}} extends Command
{
    {{each properties}}
    _{{propertyName}}:{{propertyDefaultValue}}
    {{/each}}

    constructor() {
        super();
        this.type = '{{commandArtifactId}}';
    }
    
    {{each properties}}
    get {{propertyName}}() {
        return _propertyName
    }

    set propertyName(value) {
        _propertyName = value;
    }

    {{/each}}

```

**Comment by einari** [comment]
The templates can be embedded into the DLL of the tool: 

Using the following in `.csproj`for the build tool
```xml
    <ItemGroup>
    <EmbeddedResource Include="CommandTemplate.js"/>
  </ItemGroup>
```

Then these show up as manifest resources on the assembly and can be fetched as follows:

```csharp
            var asm = typeof(Program).Assembly;
            var names = asm.GetManifestResourceNames();
            names.ForEach(Console.WriteLine);
            var stream = asm.GetManifestResourceStream("Server.CommandTemplate.js");
            var reader = new StreamReader(stream);
            var template = reader.ReadToEnd();
```

**Comment by woksin** [comment]
I need more information on how the setup/structure should be for Queries and ReadModels cc @einari

**Comment by einari** [comment]
I did some testing and with the current JavaScript client implementation, it just uses the `JSON.stringify()` approach, which then won't catch JavaScript properties at all - as these are seen as methods. We need to change the Command proxy template to be as follows:

```javascript
import { Command } from  '@dolittle/commands/Command';

export class {{commandName}} extends Command
{
    constructor() {
        super();
        this.type = '{{commandArtifactId}}';
        {{#each properties}}
        {{propertyName}} = {{propertyDefaultValue}};
        {{/each}}
    }
}
```

**Comment by einari** [comment]
For read models, very similar:

```javascript
import { Command } from  '@dolittle/readModels';

export class {{readModelName}} extends ReadModel
{
    constructor() {
        super();
        this.artifact = {
           id: '{{readModelArtifactId}}',
           generation: '{{readModelGenerationid}}'
        };
        {{#each properties}}
        {{propertyName}} = {{propertyDefaultValue}};
        {{/each}}
    }
}
```

**Comment by einari** [comment]
For queries, its slightly different - as it has not been on the backend changed for the new artifact system. So here we are relying on other information. If you have a look at [this](https://github.com/dolittle-interaction/JavaScript.Client/blob/master/Source/queries/QueryRequest.js).

```javascript
import { Query } from  '@dolittle/queries';

export class {{queryName}} extends Query
{
    constructor() {
        super();
        this.nameOfQuery = '{{queryName}}';
        this.generatedFrom = '{{clrType}}';
        {{#each queryArguments}}
        this.{{queryArgument}} = {{propertyDefaultValue}};
        {{/each}}
    }
}
```
