### ISSUE TITLE
Ability to provide custom JsonSerializerSettings.

### ISSUE THREAD

**Issue by einari** [dolittle/DotNET.SDK#70]
In order to provide custom converters and override default settings, it would be great if we could have a way to at the time of building the client to configure `JsonSerializerSettings used by `EventContentSerializer` internally in the Try* serialize / deserialize methods.

```csharp
client
   .ForMicroservice(...)
   .WithJsonSerializerSettings(_ => new JsonSerializerSettings { Converters = .... });
```

**Comment by woksin** [comment]
Hello, @einari! This seems like something we should have

**Comment by einari** [comment]
Great. I can make a stab at it and send a PR your way.
